<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MyDrive.Backup.App</RootNamespace>
    <AssemblyName>MyDrive.Backup</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyDrive.Backup.Core\MyDrive.Backup.Core.csproj" />
  </ItemGroup>
</Project>
