using System.Globalization;

namespace MyDrive.Backup.App;

public static class UiText
{
    private static readonly Dictionary<string, (string En, string Vi)> Strings = new()
    {
        ["dashboard"] = ("Dashboard", "Tổng quan"),
        ["backups"] = ("Backups", "Sao lưu"),
        ["transfers"] = ("Transfers", "Truyền tải"),
        ["activity"] = ("Activity", "Hoạt động"),
        ["settings"] = ("Settings", "Cài đặt"),
        ["account"] = ("Account", "Tài khoản"),
        ["server"] = ("Server", "Máy chủ"),
        ["storage"] = ("Storage", "Dung lượng"),
        ["protected"] = ("Protected folders", "Thư mục được bảo vệ"),
        ["files"] = ("Files backed up", "Tệp đã sao lưu"),
        ["backupSize"] = ("Backup size", "Dung lượng sao lưu"),
        ["last"] = ("Last backup", "Lần sao lưu gần nhất"),
        ["uploading"] = ("Uploading", "Đang tải lên"),
        ["speed"] = ("Speed", "Tốc độ"),
        ["remaining"] = ("Remaining", "Còn lại"),
        ["eta"] = ("Estimated time", "Thời gian ước tính"),
        ["unlimited"] = ("Unlimited", "Không giới hạn"),
        ["backupNow"] = ("Backup now", "Sao lưu ngay"),
        ["pause"] = ("Pause", "Tạm dừng"),
        ["resume"] = ("Resume", "Tiếp tục"),
        ["addFolder"] = ("Add folder", "Thêm thư mục"),
        ["open"] = ("Open", "Mở"),
        ["exit"] = ("Exit", "Thoát"),
        ["connect"] = ("Connect your server", "Kết nối máy chủ"),
        ["test"] = ("Test connection", "Kiểm tra kết nối"),
        ["signIn"] = ("Continue in browser", "Tiếp tục trên trình duyệt"),
        ["authorized"] = ("This computer is authorized.", "Máy này đã được ủy quyền."),
        ["choose"] = ("Choose a folder to protect", "Chọn thư mục cần bảo vệ"),
        ["ready"] = ("You're protected.", "Dữ liệu đã được bảo vệ."),
        ["start"] = ("Back up now", "Sao lưu ngay"),
        ["insecure"] = ("Insecure connection", "Kết nối không an toàn"),
        ["changeServer"] = ("Change server", "Đổi máy chủ"),
        ["disconnect"] = ("Disconnect", "Ngắt kết nối"),
        ["all"] = ("All", "Tất cả"),
        ["uploaded"] = ("Uploaded", "Đã tải lên"),
        ["skipped"] = ("Skipped", "Bỏ qua"),
        ["failed"] = ("Failed", "Thất bại"),
        ["deleted"] = ("Deleted", "Đã xóa"),
        ["subtitleDashboard"] = ("A quiet copy of the folders you choose.", "Bản sao yên lặng của những thư mục bạn chọn."),
        ["subtitleBackups"] = ("Each folder keeps its own schedule and destination.", "Mỗi thư mục có lịch và nơi lưu riêng."),
        ["subtitleTransfers"] = ("What is moving to your server right now.", "Những gì đang được chuyển lên máy chủ."),
        ["subtitleActivity"] = ("A local history of backups on this computer.", "Nhật ký sao lưu trên máy này."),
        ["subtitleSettings"] = ("Server, network, and how this app behaves.", "Máy chủ, mạng, và cách ứng dụng hoạt động."),
        ["notSignedIn"] = ("Not signed in", "Chưa đăng nhập"),
        ["noServer"] = ("No server yet", "Chưa có máy chủ"),
        ["serviceStarting"] = ("Starting the backup service", "Đang khởi động dịch vụ sao lưu"),
        ["serviceStartingBody"] = ("This stays in the background. No command window will open.", "Dịch vụ chạy nền. Không có cửa sổ dòng lệnh."),
        ["serviceDown"] = ("The backup service is not available", "Dịch vụ sao lưu chưa sẵn sàng"),
        ["retry"] = ("Try again", "Thử lại"),
        ["heroProtected"] = ("Protected", "Đã được bảo vệ"),
        ["heroSignIn"] = ("Sign in to start", "Đăng nhập để bắt đầu"),
        ["heroUploading"] = ("Uploading", "Đang tải lên"),
        ["heroPaused"] = ("Paused", "Đang tạm dừng"),
        ["heroBodyProtected"] = ("Changed files are copied to your server.", "Tệp thay đổi được sao sang máy chủ của bạn."),
        ["heroBodySignIn"] = ("Connect the server you run, then approve this computer in the browser.", "Kết nối máy chủ của bạn, rồi phê duyệt máy này trên trình duyệt."),
        ["heroBodyUploading"] = ("Files are on their way. You can keep using this computer.", "Tệp đang được chuyển. Bạn vẫn dùng máy bình thường."),
        ["heroBodyPaused"] = ("Backup is paused on this computer.", "Sao lưu đang tạm dừng trên máy này."),
        ["queue"] = ("In queue", "Trong hàng đợi"),
        ["network"] = ("Network", "Mạng"),
        ["workers"] = ("Workers", "Luồng tải"),
        ["noJobs"] = ("No folders yet", "Chưa có thư mục"),
        ["noJobsBody"] = ("Add a folder and it will be kept on your server.", "Thêm một thư mục để giữ bản sao trên máy chủ."),
        ["noTransfers"] = ("Nothing is transferring", "Không có tệp đang truyền"),
        ["noTransfersBody"] = ("A live view appears here while files upload.", "Khi có tệp tải lên, tiến trình sẽ hiện ở đây."),
        ["noActivity"] = ("No activity yet", "Chưa có hoạt động"),
        ["noActivityBody"] = ("Uploads, skips, and failures will be listed here.", "Tệp đã tải, đã bỏ qua, và lỗi sẽ được liệt kê ở đây."),
        ["running"] = ("Watching", "Đang theo dõi"),
        ["paused"] = ("Paused", "Tạm dừng"),
        ["remove"] = ("Remove", "Gỡ"),
        ["saveSettings"] = ("Save settings", "Lưu cài đặt"),
        ["setupIntro"] = ("Use the address of the My Drive server you run. Nothing is built in, and this app never asks for your password.", "Nhập địa chỉ máy chủ My Drive do bạn tự chạy. Ứng dụng không gắn sẵn tên miền và không hỏi mật khẩu."),
        ["setupHint"] = ("Server URL", "Địa chỉ máy chủ"),
        ["allowHttp"] = ("Allow HTTP for a development or LAN server", "Cho phép HTTP với máy chủ thử nghiệm hoặc mạng nội bộ"),
        ["connectedTo"] = ("Connected", "Đã kết nối"),
        ["approve"] = ("Approve this computer in the browser. Backup starts after that.", "Phê duyệt máy này trên trình duyệt. Sao lưu bắt đầu sau khi được duyệt."),
        ["userCode"] = ("Code", "Mã"),
        ["openLogs"] = ("View logs", "Xem nhật ký"),
        ["exportLogs"] = ("Export", "Xuất"),
        ["clearLogs"] = ("Clear", "Xóa"),
        ["rebuild"] = ("Rebuild index", "Tạo lại chỉ mục"),
        ["verify"] = ("Verify", "Kiểm tra"),
        ["noLogs"] = ("No log entries.", "Chưa có nhật ký."),
        ["logsTitle"] = ("Logs", "Nhật ký"),
        ["sectionAccount"] = ("This computer", "Máy này"),
        ["sectionBackup"] = ("Backup defaults", "Mặc định sao lưu"),
        ["sectionFilters"] = ("What to skip", "Những gì được bỏ qua"),
        ["sectionTransfer"] = ("Transfer", "Truyền tải"),
        ["sectionNetwork"] = ("Network", "Mạng"),
        ["sectionApp"] = ("This app", "Ứng dụng"),
        ["sectionAdvanced"] = ("Advanced", "Nâng cao"),
        ["backupDefaultsBody"] = ("New folders use this destination and deletion policy. Removing a folder keeps the copy already stored on the server.", "Thư mục mới dùng nơi lưu và cách xử lý xóa này. Gỡ một thư mục không xóa bản sao đã có trên máy chủ."),
        ["filtersBody"] = ("Hidden files, Windows system files, and symbolic links stay off unless you enable them.", "Tệp ẩn, tệp hệ thống Windows, và liên kết tượng trưng được bỏ qua trừ khi bạn bật."),
        ["transferBody"] = ("How many files upload at once, and how large each piece is.", "Số tệp tải cùng lúc, và kích thước mỗi phần."),
        ["networkBody"] = ("A metered connection is left alone unless you allow it. If Windows is unsure, backup continues.", "Mạng tính cước được bỏ qua trừ khi bạn cho phép. Nếu Windows không chắc, sao lưu vẫn tiếp tục."),
        ["appBody"] = ("The backup service keeps running after you close this window, without a command prompt.", "Dịch vụ sao lưu vẫn chạy sau khi đóng cửa sổ này, và không mở dòng lệnh."),
        ["advancedBody"] = ("Tokens stay out of the local database. Rebuild and verify never delete cloud files.", "Mã đăng nhập không nằm trong cơ sở dữ liệu cục bộ. Tạo lại chỉ mục và kiểm tra không xóa tệp trên mây."),
        ["defaultDestination"] = ("Default destination", "Nơi lưu mặc định"),
        ["deletionPolicy"] = ("When a local file disappears", "Khi tệp cục bộ biến mất"),
        ["keep"] = ("Keep the cloud copy", "Giữ bản trên mây"),
        ["trash"] = ("Move the cloud copy to trash", "Chuyển bản trên mây vào thùng rác"),
        ["delay"] = ("Trash the cloud copy later", "Chuyển vào thùng rác sau vài ngày"),
        ["hidden"] = ("Back up hidden files", "Sao lưu tệp ẩn"),
        ["system"] = ("Back up Windows system files", "Sao lưu tệp hệ thống Windows"),
        ["symlinks"] = ("Follow symbolic links", "Đi theo liên kết tượng trưng"),
        ["concurrent"] = ("Concurrent uploads", "Số tệp tải cùng lúc"),
        ["chunk"] = ("Chunk size", "Kích thước mỗi phần"),
        ["limit"] = ("Upload speed limit", "Giới hạn tốc độ tải lên"),
        ["wifi"] = ("Back up on Wi-Fi", "Sao lưu khi dùng Wi-Fi"),
        ["ethernet"] = ("Back up on Ethernet", "Sao lưu khi dùng Ethernet"),
        ["metered"] = ("Back up on metered networks", "Sao lưu trên mạng tính cước"),
        ["startWithWindows"] = ("Start with Windows", "Chạy cùng Windows"),
        ["background"] = ("Keep running in the background", "Tiếp tục chạy nền"),
        ["notifications"] = ("Show notifications", "Hiện thông báo"),
        ["language"] = ("Language", "Ngôn ngữ"),
        ["theme"] = ("Theme", "Giao diện"),
        ["continuous"] = ("Continuous", "Liên tục"),
        ["scheduled"] = ("Scheduled", "Theo lịch"),
        ["manual"] = ("Manual", "Thủ công"),
        ["destination"] = ("Destination", "Nơi lưu"),
        ["used"] = ("Used", "Đã dùng"),
        ["session"] = ("Uploaded this session", "Đã tải trong phiên này"),
        ["failedCount"] = ("Failed", "Lỗi"),
        ["retrying"] = ("Retrying", "Đang thử lại"),
        ["speedChart"] = ("Recent speed", "Tốc độ gần đây"),
        ["removeConfirm"] = ("Removing this folder stops future backups. Files already stored on the server stay there.", "Gỡ thư mục này sẽ ngừng sao lưu về sau. Tệp đã lưu trên máy chủ vẫn được giữ."),
        ["changeConfirm"] = ("Changing the server pauses backups for the current one. Jobs on this computer may not apply to the new server.", "Đổi máy chủ sẽ tạm dừng sao lưu của máy chủ hiện tại. Các thư mục trên máy này có thể không áp dụng cho máy chủ mới."),
        ["disconnectConfirm"] = ("Disconnect this computer? Files already on the server stay there.", "Ngắt máy này? Tệp đã có trên máy chủ vẫn được giữ."),
        ["clearConfirm"] = ("Clear the local troubleshooting log?", "Xóa nhật ký xử lý sự cố trên máy này?"),
        ["rebuildConfirm"] = ("Rebuilding the local index does not delete cloud backups. The next scan compares files again.", "Tạo lại chỉ mục cục bộ không xóa bản sao trên mây. Lần quét sau sẽ so sánh lại các tệp."),
        ["verifyConfirm"] = ("This re-reads local files and compares checksums. It does not delete cloud data.", "Thao tác này đọc lại tệp cục bộ và so sánh mã kiểm tra. Nó không xóa dữ liệu trên mây."),
    };

    public static string Language { get; set; } = "auto";

    public static string Get(string key)
    {
        if (!Strings.TryGetValue(key, out var value))
        {
            return key;
        }

        var vietnamese = Language == "vi" || (Language == "auto" && CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "vi");
        return vietnamese ? value.Vi : value.En;
    }
}
